---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

    # background: https://4kwallpapers.com/images/wallpapers/milky-way-starry-sky-night-mountains-lake-reflection-cold-5k-2880x1800-287.jpg

background: images/background-flipped-lower.png
# background: images/steampunk-squid.jpg
# cardBlur: lg # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

color: gray

headerStyle: boxedWidgets

hideVersion: true
theme: dark

layout:
  Monitoring:
    style: row
    columns: 3
      # icon: docker.png
    icon: /icons/oneui-workgroup.svg
  Syncing:
    style: row
    columns: 3
      # icon: instagram.png
    icon: /icons/oneui-gparted.svg
  Security:
    style: row
    columns: 3
#     icon: passwork.png
    icon: /icons/oneui-keyring-manager.svg
  Sites:
    style: row
    columns: 3
      # icon: azure-dns.png
    icon: samsung-internet.png
  Quick Links:
    style: row
    columns: 3
    icon: https://www.shareicon.net/data/512x512/2016/11/22/855055_multimedia_512x512.png

