version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraft-data:/data
      # - /home/henry/Minecraft/plugins:/plugins
      # - /home/henry/Minecraft/mods:/modpacks:ro
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      OPS: "The_4ngry_5quid"
      MAX_PLAYERS: 30
      VERSION: 1.20.1
      MAX_MEMORY: 14G
    tty: true
    stdin_open: true
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.minecraft.entrypoints=websecure
      - traefik.http.routers.minecraft.tls.certresolver=myresolver
      - traefik.http.routers.minecraft.rule=Host(`play.hj320mcserver.xyz`)

volumes:
  minecraft-data:
    external: true

networks:
  web:
    name: web
    external: true
