version: "3.3"
services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        restart: unless-stopped
        ports:
            - 1008:3000
        volumes:
            - /home/henry/Software/Homepage:/app/config # Make sure your local config directory exists
            - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
            - /home/henry/Software/Homepage/icons:/app/public/icons
            - /home/henry/Software/Homepage/images:/app/public/images
        networks:
            - web
        labels:
            - traefik.http.routers.homepage.rule=Host(`homepage.hj320mcserver.xyz`)
            - traefik.enable=true
            - traefik.http.routers.homepage.entrypoints=websecure
            - traefik.http.routers.homepage.tls.certresolver=myresolver
            
            # middleware redirect to make HTTP work
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            # global redirect to https for all sites
            - traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)
            - traefik.http.routers.redirs.entrypoints=web
            - traefik.http.routers.redirs.middlewares=redirect-to-https

networks:
  web:
    name: web
    external: true

