version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '2080:80' # Public HTTP Port
      - '2443:443' # Public HTTPS Port
      - '2081:81' # Admin Web Port
      - '2222:2222' # Used for SFTP.
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "henry"
      DB_MYSQL_PASSWORD: "NGINX_PASSWORD"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'NGINX_PASSWORD'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'henry'
      MYSQL_PASSWORD: 'NGINX_PASSWORD'
    volumes:
      - ./mysql:/var/lib/mysql

